import type { Config } from 'tailwindcss';

// Design tokens dari sensei_scheduler/DESIGN.md
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#757683',
        'outline-variant': '#c5c5d4',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#454652',
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#4157b6',
        primary: '#102b8c',
        'on-primary': '#ffffff',
        'primary-container': '#2e44a3',
        'on-primary-container': '#adbaff',
        'inverse-primary': '#b9c3ff',
        secondary: '#5a5f68',
        'on-secondary': '#ffffff',
        'secondary-container': '#dee2ed',
        'on-secondary-container': '#60656e',
        tertiary: '#5d2600',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#813700',
        'on-tertiary-container': '#ffaa7b',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b9c3ff',
        'on-primary-fixed': '#001257',
        'on-primary-fixed-variant': '#273d9d',
        'secondary-fixed': '#dee2ed',
        'secondary-fixed-dim': '#c2c6d1',
        'on-secondary-fixed': '#171c23',
        'on-secondary-fixed-variant': '#424750',
        'tertiary-fixed': '#ffdbca',
        'tertiary-fixed-dim': '#ffb68f',
        'on-tertiary-fixed': '#331200',
        'on-tertiary-fixed-variant': '#773200',
        'on-background': '#0b1c30',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        // Pastel kategori kelas (9 kategori, v2)
        'cat-clt': { DEFAULT: '#dbeafe', accent: '#3b82f6', text: '#1e40af' },
        'cat-bimbel': { DEFAULT: '#d1fae5', accent: '#10b981', text: '#065f46' },
        'cat-ssw': { DEFAULT: '#ffedd5', accent: '#f97316', text: '#9a3412' },
        'cat-private': { DEFAULT: '#ede9fe', accent: '#8b5cf6', text: '#5b21b6' },
        'cat-tg': { DEFAULT: '#ffe4e6', accent: '#f43f5e', text: '#9f1239' },
        'cat-benkyou': { DEFAULT: '#fef3c7', accent: '#f59e0b', text: '#92400e' },
        'cat-semi': { DEFAULT: '#ccfbf1', accent: '#14b8a6', text: '#115e59' },
        'cat-grup': { DEFAULT: '#e0e7ff', accent: '#6366f1', text: '#3730a3' },
        'cat-regular': { DEFAULT: '#e2e8f0', accent: '#64748b', text: '#334155' },
        // Netral untuk border/hover tabel (DESIGN.md: #E2E8F0, #CBD5E1, #F1F5F9, #F8FAFC)
        'border-soft': '#e2e8f0',
        'border-input': '#cbd5e1',
        'thead': '#f1f5f9',
        'hover-row': '#f8fafc',
      },
      borderRadius: {
        DEFAULT: '0.25rem', // 4px: inputs, checkboxes, small buttons
        card: '0.5rem', // 8px: cards, timeline events, modals
      },
      spacing: {
        base: '8px',
        gutter: '16px',
        'container-padding': '24px',
        'sidebar-width': '260px',
        'timeline-row-height': '64px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.02em' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
      },
      boxShadow: {
        floating: '0px 4px 12px rgba(0, 0, 0, 0.05)',
        none: 'none',
      },
    },
  },
  plugins: [],
} satisfies Config;
